2024-11-19 16:35:14,277 WARNING Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Rinat\Desktop\Pyhton_Urban\Modul_12\tests_12_4.py", line 25, in test_run
    run = rt.Runner(12, 5)
          ^^^^^^^^^^^^^^^^
  File "C:\Users\Rinat\Desktop\Pyhton_Urban\Modul_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-19 16:35:14,277 WARNING Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Rinat\Desktop\Pyhton_Urban\Modul_12\tests_12_4.py", line 15, in test_walk
    walker = rt.Runner('Вася', -5)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rinat\Desktop\Pyhton_Urban\Modul_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
